services:

#  itop_client.default_http_client:
#    class: GuzzleHttp\Client


  itop_client.rest_client:
    class: Combodo\ItopClientBundle\RestClient\RestClient
    arguments:
      - '%itop_client.http_client%'
      - '%itop_client.base_url%'
      - '%itop_client.auth_user%'
      - '%itop_client.auth_pwd%'
      - '%itop_client.extra_headers%'